version: "3.7"

services:
  api:
    container_name: api
    build: ./api
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./api:/code
    environment:
      FLASK_ENV: development
  frontend:
    container_name: frontend
    build: ./dashboard
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
