FROM node:14.9 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
RUN yarn install
RUN yarn global add react-scripts@4.0.3 --silent
COPY . ./
RUN yarn run build

FROM nginx:alpine
COPY --from=build /app/build /var/www
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]